# Generated by Django 3.1.1 on 2020-12-14 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EshopApp', '0004_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
